# Generated by Django 5.2.5 on 2025-08-12 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao_agendamento', models.DateTimeField(auto_now_add=True, verbose_name='Data da criação do agendamento')),
                ('triagem_IA_pendente', models.BooleanField(default=True)),
                ('data_hora_consulta', models.DateTimeField(verbose_name='Data e hora da consulta')),
                ('status_agendamento', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('CONCLUIDO', 'Concluído'), ('REAGENDADO', 'Reagendado')], default='PENDENTE', max_length=20, verbose_name='Status do Agendamento')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.medico', verbose_name='Médico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
        migrations.CreateModel(
            name='FichaMedicaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.TextField(max_length=255, verbose_name='Informe o motivo da consulta')),
                ('medicacao_para_sintoma', models.TextField(blank=True, default='Não informado', max_length=255, verbose_name='O paciente toma algum medicamento para resolver o problema? se sim, qual(is)')),
                ('medicamento_diario', models.TextField(blank=True, default='Não informado', max_length=255, verbose_name='O paciente toma algum medicamento no dia a dia? Se sim, qual(is)?')),
                ('alergia_geral', models.TextField(blank=True, default='Não informado', max_length=255, verbose_name='O paciente possui algum tipo de alergia? Mencione elas')),
                ('alergia_medicamento', models.TextField(blank=True, default='Não informado', max_length=255, verbose_name='Medicamentos de alergia')),
                ('possui_doencas_cronicas', models.TextField(blank=True, default='Não informado', max_length=255, verbose_name='O paciente possui alguma doença crônica? Se sim, qual(is)')),
                ('historico_familiar_de_doencas', models.TextField(blank=True, default='Não informado', max_length=255, verbose_name='Os sintomas possuem algum histórico familiar? Se sim, quem?')),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agendamento.agendamento', verbose_name='Agendamento')),
            ],
            options={
                'verbose_name': 'Ficha médica do paciente',
                'verbose_name_plural': 'Fichas médicas dos pacientes',
            },
        ),
    ]
