# Generated by Django 5.2 on 2025-08-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('tipo_email', models.CharField(max_length=50)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
