# Generated by Django 5.2.5 on 2025-09-08 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamento', '0001_initial'),
        ('triagem', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.medico', verbose_name='Médico'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='triagem_IA',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='triagem.triagemia', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='fichamedicapaciente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.paciente', verbose_name='Paciente'),
        ),
    ]
