# Generated by Django 5.2.5 on 2025-08-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChamadosFuncionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_queixa', models.TextField(verbose_name='Motivo da queixa')),
            ],
        ),
    ]
