# Generated by Django 5.2.5 on 2025-09-08 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expira_em',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 8, 19, 16, 27, 583224, tzinfo=datetime.timezone.utc)),
        ),
    ]
