# Generated by Django 5.2.5 on 2025-09-08 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_token_expira_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expira_em',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 8, 19, 21, 7, 813416, tzinfo=datetime.timezone.utc)),
        ),
    ]
