# Generated by Django 5.2 on 2025-09-09 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_token_expira_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expira_em',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 9, 1, 33, 54, 263407, tzinfo=datetime.timezone.utc)),
        ),
    ]
