# Generated by Django 5.2 on 2025-09-09 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_token_expira_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expira_em',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 9, 16, 7, 32, 634444, tzinfo=datetime.timezone.utc)),
        ),
    ]
