# Generated by Django 5.2 on 2025-09-11 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_token_expira_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expira_em',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 11, 15, 21, 24, 352256, tzinfo=datetime.timezone.utc)),
        ),
    ]
