# Generated by Django 5.2 on 2025-08-15 21:37

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10, verbose_name='Sexo')),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Formato de número inválido! formato correto: (11) 91234-5678', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')], verbose_name='Telefone')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='AdministradorSistema',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cargo', models.TextField(max_length=3, verbose_name='Cargo administrativo')),
                ('departamento', models.TextField(max_length=30, verbose_name='Departamento')),
                ('status_registro', models.CharField(choices=[('PENDENTE', 'Pendente'), ('AUTORIZADO', 'Autorizar'), ('REJEITADO', 'Rejeitar')], default='PENDENTE', max_length=10, verbose_name='Status de cadastramento')),
            ],
            options={
                'verbose_name': 'Administrador do Sistema',
                'verbose_name_plural': 'Administradores do Sistema',
            },
            bases=('usuario.usuario',),
        ),
        migrations.CreateModel(
            name='Enfermeiro',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('coren', models.CharField(max_length=20, unique=True, verbose_name='Registro COREN')),
                ('setor_atuacao', models.CharField(max_length=50, verbose_name='Setor de atuação')),
                ('status_registro', models.CharField(choices=[('PENDENTE', 'Pendente'), ('AUTORIZADO', 'Autorizar'), ('REJEITADO', 'Rejeitar')], default='PENDENTE', max_length=10, verbose_name='Status de cadastramento')),
            ],
            options={
                'verbose_name': 'Enfermeiro',
                'verbose_name_plural': 'Enfermeiros',
            },
            bases=('usuario.usuario',),
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('crm', models.CharField(max_length=20, unique=True, verbose_name='CRM')),
                ('especialidade', models.CharField(max_length=50, verbose_name='Especialidade')),
                ('status_registro', models.CharField(choices=[('PENDENTE', 'Pendente'), ('AUTORIZADO', 'Autorizar'), ('REJEITADO', 'Rejeitar')], default='PENDENTE', max_length=10, verbose_name='Status de cadastramento')),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medicos',
            },
            bases=('usuario.usuario',),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cns', models.CharField(max_length=15, unique=True, verbose_name='Carteira Nacional de Saúde (CNS)')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
            bases=('usuario.usuario',),
        ),
        migrations.CreateModel(
            name='RH',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo do RH')),
                ('departamento', models.CharField(max_length=50, verbose_name='Departamento do RH')),
            ],
            options={
                'abstract': False,
            },
            bases=('usuario.usuario',),
        ),
        migrations.CreateModel(
            name='CadastroToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=6, unique=True)),
                ('expira_em', models.DateTimeField(default=datetime.datetime(2025, 8, 15, 21, 52, 39, 729676, tzinfo=datetime.timezone.utc))),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
    ]
