# Generated by Django 5.2.5 on 2025-08-12 01:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministradorSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha')),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('status_ativo', models.BooleanField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('DESLIGADO', 'Desligado')], default=True)),
                ('status_registro', models.CharField(choices=[('PENDENTE', 'Pendente'), ('AUTORIZADO', 'Autorizar'), ('REJEITADO', 'Rejeitar')], default='PENDENTE', max_length=10, verbose_name='Status de cadastramento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10, verbose_name='Sexo')),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Formato de número inválido! formato correto: (11) 91234-5678', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')], verbose_name='Telefone')),
                ('cargo', models.TextField(max_length=3, verbose_name='Cargo administrativo')),
                ('departamento', models.TextField(max_length=30, verbose_name='Departamento')),
                ('nivel_acesso', models.TextField(choices=[('N1', 'Nivel basico'), ('N2', 'Nivel intermediario'), ('N3', 'Nivel avançado')], max_length=30, verbose_name='Nivel de acesso')),
            ],
            options={
                'verbose_name': 'Administrador do Sistema',
                'verbose_name_plural': 'Administradores do Sistema',
            },
        ),
        migrations.CreateModel(
            name='Enfermeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha')),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('status_ativo', models.BooleanField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('DESLIGADO', 'Desligado')], default=True)),
                ('status_registro', models.CharField(choices=[('PENDENTE', 'Pendente'), ('AUTORIZADO', 'Autorizar'), ('REJEITADO', 'Rejeitar')], default='PENDENTE', max_length=10, verbose_name='Status de cadastramento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10, verbose_name='Sexo')),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Formato de número inválido! formato correto: (11) 91234-5678', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')], verbose_name='Telefone')),
                ('coren', models.CharField(max_length=20, unique=True, verbose_name='Registro COREN')),
                ('setor_atuacao', models.CharField(max_length=50, verbose_name='Setor de atuação')),
            ],
            options={
                'verbose_name': 'Enfermeiro',
                'verbose_name_plural': 'Enfermeiros',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha')),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('status_ativo', models.BooleanField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('DESLIGADO', 'Desligado')], default=True)),
                ('status_registro', models.CharField(choices=[('PENDENTE', 'Pendente'), ('AUTORIZADO', 'Autorizar'), ('REJEITADO', 'Rejeitar')], default='PENDENTE', max_length=10, verbose_name='Status de cadastramento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10, verbose_name='Sexo')),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Formato de número inválido! formato correto: (11) 91234-5678', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')], verbose_name='Telefone')),
                ('crm', models.CharField(max_length=20, unique=True, verbose_name='CRM')),
                ('especialidade', models.CharField(max_length=50, verbose_name='Especialidade')),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medicos',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha')),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('status_ativo', models.BooleanField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('DESLIGADO', 'Desligado')], default=True)),
                ('status_registro', models.CharField(choices=[('PENDENTE', 'Pendente'), ('AUTORIZADO', 'Autorizar'), ('REJEITADO', 'Rejeitar')], default='PENDENTE', max_length=10, verbose_name='Status de cadastramento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10, verbose_name='Sexo')),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Formato de número inválido! formato correto: (11) 91234-5678', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')], verbose_name='Telefone')),
                ('cns', models.CharField(max_length=15, unique=True, verbose_name='Carteira Nacional de Saúde (CNS)')),
                ('nome_pai', models.CharField(max_length=100, verbose_name='Nome completo do pai')),
                ('nome_mae', models.CharField(max_length=100, verbose_name='Nome completo da mãe')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
