# Generated by Django 5.2 on 2025-09-03 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradorsistema',
            name='cargo',
            field=models.CharField(choices=[('super_admin', 'Super Administrador'), ('seguranca', 'Administrador de Segurança'), ('rede', 'Administrador de Rede'), ('banco_dados', 'Administrador de Banco de Dados'), ('infra', 'Administrador de Infraestrutura'), ('aplicacao', 'Administrador de Aplicações')], max_length=50, verbose_name='Cargo administrativo'),
        ),
        migrations.AlterField(
            model_name='administradorsistema',
            name='departamento',
            field=models.TextField(choices=[('ti', 'Tecnologia da Informação'), ('infra', 'Infraestrutura'), ('suporte', 'Suporte Técnico'), ('seguranca', 'Segurança da Informação'), ('desenvolvimento', 'Desenvolvimento de Sistemas'), ('gestao', 'Gestão e Governança de TI')], max_length=30, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='rh',
            name='setor_responsabilidade',
            field=models.CharField(choices=[('recrutamento', 'Recrutamento e Seleção'), ('treinamento', 'Treinamento e Desenvolvimento'), ('beneficios', 'Gestão de Benefícios'), ('folha', 'Folha de Pagamento')], max_length=50, verbose_name='setor de responsabilidade'),
        ),
        migrations.AlterField(
            model_name='token',
            name='expira_em',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 3, 12, 22, 59, 329288, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
    ]
