# Generated by Django 5.2 on 2025-08-10 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrotoken',
            name='expira_em',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 10, 16, 37, 6, 72288, tzinfo=datetime.timezone.utc)),
        ),
    ]
