# Generated by Django 5.2.5 on 2025-08-12 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('triagem', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_medicamento', models.CharField(max_length=150, verbose_name='Medicamento')),
                ('tarja_medicamento', models.CharField(choices=[('Tarja Preta', 'Tarja preta'), ('Tarja Vermelha', 'Tarja vermelha'), ('Tarja Amarela', 'Tarja amarela'), ('Sem Tarja', 'Sem tarja')], max_length=150, verbose_name='Tarjad do medicamento')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exame_fisico_detalhado', models.TextField(blank=True, verbose_name='Exame Físico Detalhado (Inspeção, Palpação, Percussão, Ausculta por sistemas)')),
                ('possiveis_diagnosticas', models.TextField(blank=True, verbose_name='Hipóteses Diagnósticas (possíveis diagnósticos)')),
                ('diagnostico_final', models.TextField(blank=True, verbose_name='Diagnóstico(s) Final(is) (incluir CID-10 se aplicável)')),
                ('exames_solicitados', models.TextField(blank=True, verbose_name='Exames Complementares Solicitados (Laboratoriais, Imagem, etc.)')),
                ('orientacoes', models.TextField(blank=True, verbose_name='Orientações (ex: dieta, repouso, fisioterapia)')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.medico', verbose_name='Médico Responsável')),
                ('triagem_enfermeiro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='triagem.triagemenfermeiro')),
            ],
            options={
                'verbose_name': 'Consulta médica',
                'verbose_name_plural': 'Consultas médicas',
            },
        ),
        migrations.CreateModel(
            name='ReceitaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_prescricao', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consulta.consultamedica', verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Prescrição Médica',
                'verbose_name_plural': 'Prescrições Médicas',
            },
        ),
        migrations.CreateModel(
            name='ReceitaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosagem', models.CharField(max_length=100, verbose_name='Dosagem do medicamento')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('recomendacoes', models.TextField(blank=True, verbose_name='Recomendações')),
                ('via_medicamento', models.CharField(choices=[('Oral', 'Via Oral'), ('Intramuscular', 'Via Intramuscular'), ('Subcutanea', 'Via Subcutânea'), ('Sublingual', 'Via Sublingual'), ('Endovenosa', 'Via Endovenosa'), ('Intradermica', 'Via Intradérmica'), ('Intratecal', 'Via Intratecal'), ('Intra_auricular', 'Via Intra-auricular'), ('Inalatoria', 'Via Inalatória'), ('Topica', 'Via Tópica'), ('Vaginal', 'Via Vaginal'), ('Retal', 'Via Retal'), ('Intraocular', 'Via Intraocular'), ('Intra_arterial', 'Via Intra-arterial'), ('Epidural', 'Via Epidural'), ('Intranasal', 'Via Intranasal'), ('Intraperitoneal', 'Via Intraperitoneal')], max_length=100)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consulta.medicamento')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.receitamedica')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
    ]
