# Generated by Django 5.2 on 2025-08-24 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consulta', '0001_initial'),
        ('triagem', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.medico', verbose_name='Médico Responsável'),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='triagem_enfermeiro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='triagem.triagemenfermeiro'),
        ),
        migrations.AddField(
            model_name='receitaitem',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consulta.medicamento'),
        ),
        migrations.AddField(
            model_name='receitamedica',
            name='consulta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consulta.consultamedica', verbose_name='Consulta'),
        ),
        migrations.AddField(
            model_name='receitaitem',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.receitamedica'),
        ),
    ]
