# Generated by Django 5.2 on 2025-09-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultamedica',
            old_name='diagnostico_final',
            new_name='diagnostico',
        ),
        migrations.RemoveField(
            model_name='consultamedica',
            name='exame_fisico_detalhado',
        ),
        migrations.RemoveField(
            model_name='consultamedica',
            name='possiveis_diagnosticas',
        ),
    ]
