# Generated by Django 5.2.5 on 2025-09-08 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamento', '0002_initial'),
        ('triagem', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagemenfermeiro',
            name='enfermeiro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.enfermeiro', verbose_name='Enfermeiro Responsável'),
        ),
        migrations.AddField(
            model_name='triagemia',
            name='ficha_medica_paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agendamento.fichamedicapaciente', verbose_name='Agendamento do paciente'),
        ),
    ]
