# Generated by Django 5.2 on 2025-08-24 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriagemIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico_IA', models.TextField(verbose_name='Diagnóstico da IA')),
                ('prioridade_IA', models.CharField(blank=True, choices=[('EMERGENCIA - VERMELHO', 'EMERGÊNCIA (vermelho)'), ('MUITO_URGENTE - LARANJA', 'MUITO URGENTE (laranja)'), ('URGENTE - AMARELO', 'URGENTE (amarelo)'), ('POUCO_URGENTE - VERDE', 'POUCO URGENTE (verde)'), ('NAO_URGENTE - AZUL', 'NÃO URGENTE (azul)')], max_length=40, null=True, verbose_name='Prioridade Classificada pela IA')),
                ('status_agendamento', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado')], default='PENDENTE', max_length=20, verbose_name='Status do Agendamento')),
            ],
        ),
        migrations.CreateModel(
            name='TriagemEnfermeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressao_arterial', models.CharField(blank=True, default='Procedimento não realizado', max_length=10, verbose_name='Pressão Arterial (mmHg)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('frequencia_cardiaca', models.IntegerField(blank=True, default=0, null=True, verbose_name='Frequência Cardíaca (bpm)')),
                ('frequencia_respiratoria', models.IntegerField(blank=True, default=0, null=True, verbose_name='Frequência Respiratória (rpm)')),
                ('saturacao_oxigenio', models.IntegerField(blank=True, default=0, null=True, verbose_name='Saturação de Oxigênio (%)')),
                ('glicemia_capilar', models.IntegerField(blank=True, default=0, null=True, verbose_name='Glicemia Capilar (mg/dL)')),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agendamento.agendamento', verbose_name='Agendamento do Paciente')),
            ],
            options={
                'verbose_name': 'Triagem do enfermeiro(a)',
                'verbose_name_plural': 'Triagens do enfermeiros(as)',
            },
        ),
    ]
