# Generated by Django 5.2 on 2025-09-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triagemenfermeiro',
            options={'ordering': ['-data_criacao_triagem'], 'verbose_name': 'Triagem do enfermeiro(a)', 'verbose_name_plural': 'Triagens do enfermeiros(as)'},
        ),
        migrations.RenameField(
            model_name='triagemenfermeiro',
            old_name='daca_criacao_triagem',
            new_name='data_criacao_triagem',
        ),
    ]
